// flow-typed signature: a987c887fdaf0dc6b136fa3a15bf58cc
// flow-typed version: <<STUB>>/flow-enums-runtime_v^0.0.6/flow_v0.175.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-enums-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-enums-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-enums-runtime/__tests__/no-weakmap' {
  declare module.exports: any;
}

declare module 'flow-enums-runtime/__tests__/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-enums-runtime/__tests__/no-weakmap.js' {
  declare module.exports: $Exports<'flow-enums-runtime/__tests__/no-weakmap'>;
}
declare module 'flow-enums-runtime/__tests__/tests.js' {
  declare module.exports: $Exports<'flow-enums-runtime/__tests__/tests'>;
}
declare module 'flow-enums-runtime/index' {
  declare module.exports: $Exports<'flow-enums-runtime'>;
}
declare module 'flow-enums-runtime/index.js' {
  declare module.exports: $Exports<'flow-enums-runtime'>;
}
